// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXu6ixpxulcb25qMc-IHgp-sR3J2ULjn4',
    appId: '1:638417643329:web:bd13d5d8dec7602ed6e3c0',
    messagingSenderId: '638417643329',
    projectId: 'movie-6314f',
    authDomain: 'movie-6314f.firebaseapp.com',
    storageBucket: 'movie-6314f.appspot.com',
    measurementId: 'G-SLHWP5V0KD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6x1JCszw_Hp-cJiHRFm_i7iYxRe8Yqo0',
    appId: '1:638417643329:android:39d351d70acdc056d6e3c0',
    messagingSenderId: '638417643329',
    projectId: 'movie-6314f',
    storageBucket: 'movie-6314f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLSYQejzkTX48xJ7FAwTYC_b9KKleRrMk',
    appId: '1:638417643329:ios:7a4da79afefaf4c3d6e3c0',
    messagingSenderId: '638417643329',
    projectId: 'movie-6314f',
    storageBucket: 'movie-6314f.appspot.com',
    iosClientId: '638417643329-i75fou0u16igl6dlvhq9mri6hi2m1gak.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLSYQejzkTX48xJ7FAwTYC_b9KKleRrMk',
    appId: '1:638417643329:ios:7a4da79afefaf4c3d6e3c0',
    messagingSenderId: '638417643329',
    projectId: 'movie-6314f',
    storageBucket: 'movie-6314f.appspot.com',
    iosClientId: '638417643329-i75fou0u16igl6dlvhq9mri6hi2m1gak.apps.googleusercontent.com',
    iosBundleId: 'com.example.movieApp',
  );
}
